name: amplify_icons
description: Collection of beautiful and well-designed icons from AWS Amplify UI Kit
version: 0.0.1
homepage: https://github.com/hanmajid/amplify_icons
issue_tracker: https://github.com/hanmajid/amplify_icons/issues
repository: https://github.com/hanmajid/amplify_icons
funding:
  - https://github.com/sponsors/hanmajid

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: AmplifyIcons
      fonts:
        - asset: assets/AmplifyIcons.ttf

topics:
  - assets
  - icons
  - ui

screenshots:
  - description: 'AWS Amplify icons'
    path: amplify-icons.png